name: call-update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

permissions:
  contents: write
  packages: write

jobs:
  call:
    uses: edbfi/base-image/.github/workflows/update-on-call.yml@workflows
    secrets: inherit
